# All options and their defaults.
#
# This is executed separately to the main configuration
# so that options are set before parsing the rest of the config.

# DO NOT USE -o IN YOUR OWN CONFIGURATION
set -ogq @kanagawa_flavor "mocha"

set -ogq @kanagawa_status_background "default"

# Menu styling options
set -ogq @kanagawa_menu_selected_style "fg=#{@thm_fg},bold,bg=#{@thm_border}"

# Pane styling options (DO NOT USE -o IN YOUR OWN CONFIGURATION)
set -ogq @kanagawa_pane_status_enabled "no" # set to "yes" to enable
set -ogq @kanagawa_pane_border_status "off" # set to "yes" to enable
set -ogq @kanagawa_pane_border_style "fg=#{@thm_border}"
set -ogq @kanagawa_pane_active_border_style "##{?pane_in_mode,fg=#{@thm_light_purple},##{?pane_synchronized,fg=#{@thm_dark_purple},fg=#{@thm_light_purple}}}"
set -ogq @kanagawa_pane_left_separator "█"
set -ogq @kanagawa_pane_middle_separator "█"
set -ogq @kanagawa_pane_right_separator "█"
set -ogq @kanagawa_pane_color "#{@thm_green}"
set -ogq @kanagawa_pane_background_color "#{@thm_bg_alt}"
set -ogq @kanagawa_pane_default_text "##{b:pane_current_path}"
set -ogq @kanagawa_pane_default_fill "number"
set -ogq @kanagawa_pane_number_position "left" # right, left

# NOTE: Changes to make the option names more intuitive and more closely follow
# the tmux naming conventions.
# @kanagawa_window_current_background -> @kanagawa_window_current_number_color
# @kanagawa_window_current_color      -> @kanagawa_window_current_text_color
# @kanagawa_window_default_background -> @kanagawa_window_number_color
# @kanagawa_window_default_color      -> @kanagawa_window_text_color
# @kanagawa_window_status             -> @kanagawa_window_flags
#
# Removed:
# @kanagawa_window_default_fill, @kanagawa_window_current_fill
# Just set the number and text colors.

# Window options (DO NOT USE -o IN YOUR OWN CONFIGURATION)
set -ogq @kanagawa_window_status_style "basic" # basic, rounded, slanted, custom, or none
set -ogq @kanagawa_window_text_color "#{@thm_bg_alt}"
set -ogq @kanagawa_window_number_color "#{@thm_text_alt}"
set -ogq @kanagawa_window_text " #T"
set -ogq @kanagawa_window_number "#I"
set -ogq @kanagawa_window_current_text_color "#{@thm_text_alt_2}"
set -ogq @kanagawa_window_current_number_color "#{@thm_dark_purple}"
set -ogq @kanagawa_window_current_text " #T"
set -ogq @kanagawa_window_current_number "#I"
set -ogq @kanagawa_window_number_position "left"

# Window flags
set -ogq @kanagawa_window_flags "none"
set -ogq @kanagawa_window_flags_icon_last " 󰖰" # -
set -ogq @kanagawa_window_flags_icon_current " 󰖯" # *
set -ogq @kanagawa_window_flags_icon_zoom " 󰁌" # Z
set -ogq @kanagawa_window_flags_icon_mark " 󰃀" # M
set -ogq @kanagawa_window_flags_icon_silent " 󰂛" # ~
set -ogq @kanagawa_window_flags_icon_activity " 󱅫" # #
set -ogq @kanagawa_window_flags_icon_bell " 󰂞" # !
# Matches icon order when using `#F` (`#!~[*-]MZ`)
set -ogq @kanagawa_window_flags_icon_format "##{?window_activity_flag,#{E:@kanagawa_window_flags_icon_activity},}##{?window_bell_flag,#{E:@kanagawa_window_flags_icon_bell},}##{?window_silence_flag,#{E:@kanagawa_window_flags_icon_silent},}##{?window_active,#{E:@kanagawa_window_flags_icon_current},}##{?window_last_flag,#{E:@kanagawa_window_flags_icon_last},}##{?window_marked_flag,#{E:@kanagawa_window_flags_icon_mark},}##{?window_zoomed_flag,#{E:@kanagawa_window_flags_icon_zoom},} "

# Status line options (DO NOT USE -o IN YOUR OWN CONFIGURATION)
set -ogq @kanagawa_status_left_separator ""
set -ogq @kanagawa_status_middle_separator ""
set -ogq @kanagawa_status_right_separator " "
set -ogq @kanagawa_status_connect_separator "yes" # yes, no

# Maintain backwards compatibility. Use @kanagawa_status_module_bg_color if it is set.
set -ogq @kanagawa_status_module_text_bg "#{?@kanagawa_status_module_bg_color,#{E:@kanagawa_status_module_bg_color},#{@thm_bg_alt}}"
