local colors = import 'colors.libsonnet';
local util = import 'utils.libsonnet';
{
  'kanagawa_wave_tmux.conf': util.manifestTmux(util.Theme {
    white: colors.oldWhite,
    dark_purple: colors.oniViolet,
    light_purple: colors.oniViolet2,
    red: colors.waveRed,
    pink: colors.sakuraPink,
    orange: colors.surimiOrange,
    yellow: colors.carpYellow,
    green: colors.autumnGreen,
    teal: colors.waveAqua2,
    light_blue: colors.springBlue,
    dark_blue: colors.crystalBlue,
    text_alt: colors.sumiInk6,
    text_alt_2: colors.katanaGray,
    border: colors.fujiGray,
    bg: colors.sumiInk3,
    bg_alt: colors.sumiInk4,
    fg: colors.fujiWhite,
    fg_dark: colors.sumiInk0,
  }),
  'kanagawa_dragon_tmux.conf': util.manifestTmux(util.Theme {
    white: colors.oldWhite,
    dark_purple: colors.springViolet1,
    light_purple: colors.dragonViolet,
    red: colors.dragonRed,
    pink: colors.dragonPink,
    orange: colors.dragonOrange,
    yellow: colors.dragonYellow,
    green: colors.dragonGreen2,
    teal: colors.dragonTeal,
    light_blue: colors.springBlue,
    dark_blue: colors.crystalBlue,
    text_alt: colors.dragonAsh,
    text_alt_2: colors.katanaGray,
    border: colors.dragonBlack6,
    bg: colors.dragonBlack3,
    bg_alt: colors.dragonBlack4,
    fg: colors.dragonWhite,
    fg_dark: colors.dragonBlack0,
  }),
}
