local conifer = import 'conifer.libsonnet';
local kanagawa = import 'kanagawa.libsonnet';
local util = import 'utils.libsonnet';
{
  'kanagawa_wave_tmux.conf': util.manifestTmux(util.Theme {
    white: kanagawa.oldWhite,
    dark_purple: kanagawa.oniViolet,
    light_purple: kanagawa.oniViolet2,
    red: kanagawa.waveRed,
    pink: kanagawa.sakuraPink,
    orange: kanagawa.surimiOrange,
    yellow: kanagawa.carpYellow,
    green: kanagawa.autumnGreen,
    teal: kanagawa.waveAqua2,
    light_blue: kanagawa.springBlue,
    dark_blue: kanagawa.crystalBlue,
    text_alt: kanagawa.sumiInk6,
    text_alt_2: kanagawa.katanaGray,
    border: kanagawa.fujiGray,
    bg: kanagawa.sumiInk3,
    bg_alt: kanagawa.sumiInk4,
    fg: kanagawa.fujiWhite,
    fg_dark: kanagawa.sumiInk0,
  }),
  'kanagawa_dragon_tmux.conf': util.manifestTmux(util.Theme {
    white: kanagawa.oldWhite,
    dark_purple: kanagawa.springViolet1,
    light_purple: kanagawa.dragonViolet,
    red: kanagawa.dragonRed,
    pink: kanagawa.dragonPink,
    orange: kanagawa.dragonOrange,
    yellow: kanagawa.dragonYellow,
    green: kanagawa.dragonGreen2,
    teal: kanagawa.dragonTeal,
    light_blue: kanagawa.springBlue,
    dark_blue: kanagawa.crystalBlue,
    text_alt: kanagawa.dragonAsh,
    text_alt_2: kanagawa.katanaGray,
    border: kanagawa.dragonBlack6,
    bg: kanagawa.dragonBlack3,
    bg_alt: kanagawa.dragonBlack4,
    fg: kanagawa.dragonWhite,
    fg_dark: kanagawa.dragonBlack0,
  }),
  // calling it kanagawa for ease of using the same things
  'kanagawa_conifer_tmux.conf': util.manifestTmux(util.Theme {
    white: conifer.fg0,
    dark_purple: conifer.dark_purple,
    light_purple: conifer.fog,
    red: conifer.err,
    pink: conifer.err,
    orange: conifer.orange,
    yellow: conifer.yellow,
    green: conifer.green,
    teal: conifer.bud,
    light_blue: conifer.azure,
    dark_blue: conifer.moss,
    text_alt: conifer.fog,
    text_alt_2: conifer.lichen,
    border: conifer.bg6,
    bg: conifer.bg1,
    bg_alt: conifer.bg2,
    fg: conifer.fg1,
    fg_dark: conifer.bg0,
  }),
}
