# vim:set ft=tmux:
%hidden MODULE_NAME="kube"

# Requires https://github.com/jonmosco/kube-tmux

set -ogq "@kanagawa_${MODULE_NAME}_icon" "󱃾 "
set -ogqF "@kanagawa_${MODULE_NAME}_color" "#{E:@thm_dark_blue}"
set -ogqF "@kanagawa_kube_context_color" "#{E:@thm_red}"
set -ogqF "@kanagawa_kube_namespace_color" "#{E:@thm_light_blue}"
set -ogq "@kanagawa_${MODULE_NAME}_text" \
   " #(\${TMUX_PLUGIN_MANAGER_PATH}kube-tmux/kube.tmux 250 #{@kanagawa_kube_context_color} #{@kanagawa_kube_namespace_color})"

source -F "#{d:current_file}/../utils/status_module.conf"
