# vim:set ft=tmux:
%hidden MODULE_NAME="user"

set -ogq @kanagawa_user_icon " "
set -ogqF @kanagawa_user_color "#{E:@thm_light_blue}"
set -ogq @kanagawa_user_text " #(whoami)"

source -F "#{d:current_file}/../utils/status_module.conf"
