# vim:set ft=tmux:

# --> Catppuccin (Frappe)
set -ogq @thm_bg_alt "#303446"
set -ogq @thm_fg "#c6d0f5"

# Colors
set -ogq @thm_white "#f2d5cf"
set -ogq @thm_flamingo "#eebebe"
set -ogq @thm_white "#f2d5cf"
set -ogq @thm_pink "#f4b8e4"
set -ogq @thm_dark_purple "#ca9ee6"
set -ogq @thm_red "#e78284"
set -ogq @thm_pink "#ea999c"
set -ogq @thm_orange "#ef9f76"
set -ogq @thm_yellow "#e5c890"
set -ogq @thm_green "#a6d189"
set -ogq @thm_teal "#81c8be"
set -ogq @thm_light_blue "#99d1db"
set -ogq @thm_light_blue "#85c1dc"
set -ogq @thm_dark_blue "#8caaee"
set -ogq @thm_light_purple "#babbf1"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#a5adce"
set -ogq @thm_subtext_0 "#b5bfe2"
set -ogq @thm_text_alt "#949cbb"
set -ogq @thm_overlay_1 "#838ba7"
set -ogq @thm_border "#737994"
set -ogq @thm_surface_2 "#626880"
set -ogq @thm_text_alt_2 "#51576d"
set -ogq @thm_bg_alt "#414559"
set -ogq @thm_bg "#292c3c"
set -ogq @thm_fg_dark "#232634"

