# vim:set ft=tmux:

# --> Kanagawa (Wave)

# NOTE: These colors were documented as 'popup and floats'

set -ogq @thm_blue_1 "#223249"
set -ogq @thm_blue_2 "#2D4F67"

# NOTE: The winter and autumn colors are commented as _Diff_ and _Git_ in kanagawa.nvim

set -ogq @thm_winter_green "#2B3328"
set -ogq @thm_winter_yellow "#49443C"
set -ogq @thm_winter_red "#43242B"
set -ogq @thm_winter_blue "#252535"

set -ogq @thm_autumn_green "#76946A"
set -ogq @thm_autumn_red "#C34043"
set -ogq @thm_autumn_yellow "#DCA561"

# NOTE: These colors were marked as Diag colors

set -ogq @thm_samurai_red "#E82424"
set -ogq @thm_ronin_yellow "#FF9E3B"
set -ogq @thm_aqua_1 "#6A9489"

# NOTE: Marked as Fg and Comments

set -ogq @thm_old_white "#C8C093"
set -ogq @thm_fuji_white "#DCD7BA"
set -ogq @thm_fuji_gray "#727169"

# NOTE: The rest are generally undocumented

set -ogq @thm_sumi_ink_0 "#16161D"
set -ogq @thm_sumi_ink_1 "#181820"
set -ogq @thm_sumi_ink_2 "#1A1A22"
set -ogq @thm_sumi_ink_3 "#1F1F28"
set -ogq @thm_sumi_ink_4 "#2A2A37"
set -ogq @thm_sumi_ink_5 "#363646"
set -ogq @thm_sumi_ink_6 "#54546D"

set -ogq @thm_oni_violet_1 "#957FB8"
set -ogq @thm_oni_violet_2 "#B8B4D0"

set -ogq @thm_crystal_blue "#7E9CD8"

set -ogq @thm_spring_violet_1 "#938AA9"
set -ogq @thm_spring_violet_2 "#9CABCA"

set -ogq @thm_spring_blue "#7FB4CA"
set -ogq @thm_spring_green "#98BB6C"

set -ogq @thm_wave_aqua_2 "#7AA89F"

set -ogq @thm_boat_yellow_1 "#938056"
set -ogq @thm_boat_yellow_2 "#C0A36E"
set -ogq @thm_carp_yellow "#E6C384"

set -ogq @thm_sakura_pink "#D27E99"
set -ogq @thm_wave_red "#E46876"
set -ogq @thm_orange_red "#FF5D62"
set -ogq @thm_surimi_orange "#FFA066"
set -ogq @thm_katana_gray "#717C7C"

# HACK: cross flavor colors for built-in themes
set -ogq @thm_white "#C8C093"
set -ogq @thm_dark_purple "#957FB8"
set -ogq @thm_light_purple "#B8B4D0"
set -ogq @thm_red "#E46876"
set -ogq @thm_pink "#D27E99"
set -ogq @thm_orange "#FFA066"
set -ogq @thm_yellow "#E6C384"
set -ogq @thm_green "#76946A"
set -ogq @thm_teal "#7AA89F"
set -ogq @thm_light_blue "#7FB4CA"
set -ogq @thm_dark_blue "#7E9CD8"

set -ogq @thm_text_alt "#54546D"
set -ogq @thm_text_alt_2 "#717C7C"
set -ogq @thm_border "#727169"
set -ogq @thm_bg "#1F1F28"
set -ogq @thm_bg_alt "#2A2A37"
set -ogq @thm_fg "#DCD7BA"
set -ogq @thm_fg_dark "#16161D"


# set -ogq @thm_white "#{@thm_old_white}"
# set -ogq @thm_dark_purple "#{@thm_oni_violet_1}"
# set -ogq @thm_light_purple "#{@thm_oni_violet_2}"
# set -ogq @thm_red "#{@thm_wave_red}"
# set -ogq @thm_pink "#{@thm_sakura_pink}"
# set -ogq @thm_orange "#{@thm_surimi_orange}"
# set -ogq @thm_yellow "#{@thm_carp_yellow}"
# set -ogq @thm_green "#{@thm_autumn_green}"
# set -ogq @thm_teal "#{@thm_wave_aqua_2}"
# set -ogq @thm_light_blue "#{@thm_spring_blue}"
# set -ogq @thm_dark_blue "#{@thm_crystal_blue}"
#
# set -ogq @thm_text_alt "#{@thm_sumi_ink_6}"
# set -ogq @thm_text_alt_2 "#{@thm_katana_gray}"
# set -ogq @thm_border "#{@thm_fuji_gray}"
# set -ogq @thm_bg "#{@thm_sumi_ink_3}"
# set -ogq @thm_bg_alt "#{@thm_sumi_ink_4}"
# set -ogq @thm_fg "#{@thm_fuji_white}"

