set -ogq @thm_bg "#161716"
set -ogq @thm_bg_alt "#202020"
set -ogq @thm_border "#727272"
set -ogq @thm_dark_blue "#60B197"
set -ogq @thm_dark_purple "#52354f"
set -ogq @thm_fg "#D6D6D6"
set -ogq @thm_fg_dark "#151515"
set -ogq @thm_green "#85B884"
set -ogq @thm_light_blue "#6196C2"
set -ogq @thm_light_purple "#576F82"
set -ogq @thm_orange "#F6AD6C"
set -ogq @thm_pink "#C07F7A"
set -ogq @thm_red "#C07F7A"
set -ogq @thm_teal "#B3DBA9"
set -ogq @thm_text_alt "#576F82"
set -ogq @thm_text_alt_2 "#ABBAB5"
set -ogq @thm_white "#E1E1E1"
set -ogq @thm_yellow "#FFE591"