set -ogq @thm_bg "#181616"
set -ogq @thm_bg_alt "#282727"
set -ogq @thm_border "#625e5a"
set -ogq @thm_dark_blue "#7E9CD8"
set -ogq @thm_dark_purple "#938AA9"
set -ogq @thm_fg "#c5c9c5"
set -ogq @thm_fg_dark "#0d0c0c"
set -ogq @thm_green "#8a9a7b"
set -ogq @thm_light_blue "#7FB4CA"
set -ogq @thm_light_purple "#8992a7"
set -ogq @thm_orange "#b6927b"
set -ogq @thm_pink "#a292a3"
set -ogq @thm_red "#c4746e"
set -ogq @thm_teal "#949fb5"
set -ogq @thm_text_alt "#737c73"
set -ogq @thm_text_alt_2 "#717C7C"
set -ogq @thm_white "#C8C093"
set -ogq @thm_yellow "#c4b28a"
